# -*- coding: utf-8 -*-
"""road_sign_model_ready.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TBrN9cjGUJ_KNgsIp7HEjIWrYLUBo4bK
"""

from fastai.vision.all import *
import torch

!unzip /content/drive/MyDrive/Datasets/Road_signs_dataset/road_sign_dataset.zip -d /content/dataset

path = Path('/content/dataset/road_sign_dataset')

path.ls()

dblock = DataBlock(blocks = (ImageBlock, CategoryBlock),
                   get_items = get_image_files,
                   splitter = RandomSplitter(valid_pct=0.2, seed=42),
                   get_y = parent_label,
                   item_tfms = Resize(224),
                   batch_tfms = aug_transforms())

dls = dblock.dataloaders(path)

dls.show_batch()

learn = cnn_learner(dls, resnet34, metrics = accuracy)

learn.lr_find()

learn.fine_tune(5, 3e-3)

learn.export('road_sign_model.pkl')

model = load_learner('/content/drive/MyDrive/Datasets/Road_signs_dataset/road_sign_model (1).pkl')

from ipywidgets import widgets
upload = widgets.FileUpload()
upload

img = PILImage.create(upload.data[-1]) # rasm
pred, _, prob = model.predict(img) # bashorat qilish (predict)
print(pred)
pred_index = model.dls.vocab.o2i[str(pred)]

predicted_class_prob = prob[pred_index].item() * 100
print(f'Probability: {predicted_class_prob:.2f}%')
img